# Generated by Django 5.2.5 on 2025-12-27 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assets/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='music/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Proyecto sin título', max_length=255)),
                ('script_text', models.TextField()),
                ('engine', models.CharField(choices=[('edge', 'Edge TTS'), ('elevenlabs', 'ElevenLabs')], default='edge', max_length=20)),
                ('aspect_ratio', models.CharField(choices=[('landscape', 'Horizontal (16:9)'), ('portrait', 'Vertical (9:16 - Shorts)')], default='landscape', max_length=20)),
                ('voice_id', models.CharField(blank=True, help_text='ID de la voz o nombre (Edge/ElevenLabs)', max_length=255, null=True)),
                ('music_volume', models.FloatField(default=0.15, help_text='Volumen de la música (0.0 a 1.0)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('output_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('source_path', models.CharField(blank=True, help_text='Path to local folder containing script and assets', max_length=1024)),
                ('visual_prompts', models.TextField(blank=True, help_text='Prompts generados para las imágenes y videos del guion')),
                ('log_output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('background_music', models.ForeignKey(blank=True, help_text='Música de fondo para el video', null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.music')),
            ],
        ),
    ]
