# Generated by Django 5.2.5 on 2025-12-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='dynamic_pan',
            field=models.BooleanField(default=False, help_text='Activar desplazamiento dinámico en imágenes'),
        ),
    ]
