# Generated by Django 5.2.5 on 2026-01-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_videoproject_dynamic_pan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoproject',
            name='dynamic_pan',
        ),
    ]
